# Generated by Django 3.2.12 on 2022-04-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('excerpt', models.TextField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('picture', models.ImageField(upload_to='img')),
            ],
        ),
    ]
